###
# This is the place to override the opsworks_initial_setup cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "opsworks_initial_setup/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###
default[:opsworks_initial_setup][:bind_mounts][:mounts] = {}
